import React, { useEffect, useState } from 'react';
import { Question, QuizResult, getModuleInfo } from '../types';
// @ts-ignore
import { jsPDF } from 'jspdf';

interface ResultScreenProps {
  result: QuizResult;
  onRetest: () => void;
  onHome: () => void;
  questions: Question[];
}

const ResultScreen: React.FC<ResultScreenProps> = ({ result, onRetest, onHome, questions: allQuestions }) => {
  const [showDetails, setShowDetails] = useState(false);
  const [animatedPercentage, setAnimatedPercentage] = useState(0);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const timer = setTimeout(() => {
      const interval = setInterval(() => {
        setAnimatedPercentage(prev => {
          if (prev >= result.percentage) { clearInterval(interval); return result.percentage; }
          return prev + 1;
        });
      }, 20);
    }, 700);
    return () => clearTimeout(timer);
  }, [result.percentage]);

  const getGradeConfig = () => {
    if (result.percentage >= 90) return { color: 'text-emerald-400', bg: 'from-emerald-500/15 to-green-500/15 border-emerald-500/20', circle: '#10b981', glow: 'glow-green', ringBg: 'rgba(16,185,129,0.15)' };
    if (result.percentage >= 75) return { color: 'text-teal-400', bg: 'from-teal-500/15 to-cyan-500/15 border-teal-500/20', circle: '#14b8a6', glow: 'glow-teal', ringBg: 'rgba(20,184,166,0.15)' };
    if (result.percentage >= 60) return { color: 'text-amber-400', bg: 'from-amber-500/15 to-orange-500/15 border-amber-500/20', circle: '#f59e0b', glow: 'glow-amber', ringBg: 'rgba(245,158,11,0.15)' };
    return { color: 'text-red-400', bg: 'from-red-500/15 to-pink-500/15 border-red-500/20', circle: '#ef4444', glow: 'glow-red', ringBg: 'rgba(239,68,68,0.15)' };
  };

  const gc = getGradeConfig();
  const weakAreas = Object.entries(result.moduleScores).filter(([, s]) => s.total > 0 && (s.correct / s.total) < 0.7).map(([m]) => m);
  const strongAreas = Object.entries(result.moduleScores).filter(([, s]) => s.total > 0 && (s.correct / s.total) >= 0.8).map(([m]) => m);

  const formatTime = (seconds: number) => { const m = Math.floor(seconds / 60); const s = seconds % 60; return `${m}m ${s}s`; };

  const downloadCertificate = () => {
    if (result.percentage < 70) { alert('Certificate available for 70%+ scores only'); return; }
    const doc = new jsPDF('landscape');
    doc.setFillColor(12, 18, 34); doc.rect(0, 0, 297, 210, 'F');
    doc.setDrawColor(20, 184, 166); doc.setLineWidth(3); doc.rect(10, 10, 277, 190);
    doc.setDrawColor(16, 185, 129); doc.setLineWidth(1); doc.rect(15, 15, 267, 180);
    doc.setTextColor(255, 255, 255); doc.setFontSize(14); doc.text('108 EMERGENCY MEDICAL SERVICES', 148.5, 35, { align: 'center' });
    doc.setTextColor(20, 184, 166); doc.setFontSize(28); doc.text('CERTIFICATE OF COMPLETION', 148.5, 55, { align: 'center' });
    doc.setTextColor(200, 200, 200); doc.setFontSize(12); doc.text('This is to certify that', 148.5, 75, { align: 'center' });
    doc.setTextColor(255, 255, 255); doc.setFontSize(24); doc.text(result.emtName.toUpperCase(), 148.5, 92, { align: 'center' });
    doc.setTextColor(200, 200, 200); doc.setFontSize(10); doc.text(`EMT ID: ${result.emtId}`, 148.5, 102, { align: 'center' });
    doc.setFontSize(12); doc.text('has successfully completed the EMT Knowledge Assessment', 148.5, 118, { align: 'center' });
    doc.setTextColor(16, 185, 129); doc.setFontSize(20); doc.text(`Score: ${result.score}/${result.total} (${result.percentage}%)`, 148.5, 138, { align: 'center' });
    doc.setTextColor(20, 184, 166); doc.setFontSize(16);
    const cleanGrade = result.grade.replace(/[🌟✅⚠️🔴]/g, '').trim();
    doc.text(`Grade: ${cleanGrade}`, 148.5, 152, { align: 'center' });
    doc.setTextColor(150, 150, 150); doc.setFontSize(10);
    const dateStr = new Date(result.date).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });
    doc.text(`Date: ${dateStr}`, 80, 175); doc.text(`Certificate ID: ${result.id}`, 180, 175);
    doc.setTextColor(100, 100, 100); doc.setFontSize(8); doc.text('Auto-generated by EMT Knowledge Test System', 148.5, 190, { align: 'center' });
    doc.save(`EMT_Certificate_${result.emtName.replace(/\s/g, '_')}_${result.id}.pdf`);
  };

  const circumference = 2 * Math.PI * 62;
  const strokeDashoffset = circumference - (animatedPercentage / 100) * circumference;

  return (
    <div className="min-h-screen bg-[#0c1222] text-white relative overflow-hidden">
      <div className="absolute inset-0 pointer-events-none">
        <div className="absolute top-[-20%] left-[50%] -translate-x-1/2 w-[600px] h-[600px] rounded-full blur-[150px]" style={{ background: gc.ringBg }}></div>
        <div className="absolute inset-0" style={{ backgroundImage: 'radial-gradient(rgba(255,255,255,0.015) 1px, transparent 1px)', backgroundSize: '40px 40px' }}></div>
      </div>

      <div className={`max-w-4xl mx-auto px-4 py-6 relative z-10 transition-all duration-700 ${mounted ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}`}>
        <div className={`glass-card bg-gradient-to-br ${gc.bg} rounded-3xl p-6 mb-6 border`}>
          <div className="flex flex-col items-center">
            <div className={`relative w-44 h-44 mb-5 ${gc.glow} rounded-full`}>
              <svg className="w-full h-full transform -rotate-90">
                <circle cx="88" cy="88" r="62" fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth="6" />
                <circle cx="88" cy="88" r="62" fill="none" stroke={gc.circle} strokeWidth="6" strokeLinecap="round"
                  strokeDasharray={circumference} strokeDashoffset={strokeDashoffset} className="transition-all duration-1000 ease-out" />
              </svg>
              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <span className={`text-5xl font-black ${gc.color}`}>{animatedPercentage}%</span>
                <span className="text-xs text-gray-500 font-mono mt-1">{result.score}/{result.total}</span>
              </div>
            </div>
            <div className="text-center">
              <h1 className="text-2xl font-black mb-1">
                {result.percentage >= 70 ? '🎉' : '📚'} Your Result
              </h1>
              <p className={`text-lg font-black ${gc.color}`}>{result.grade}</p>
              <p className="text-xs text-gray-500 mt-1 font-medium">{result.emtName} • {result.emtId}</p>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-4 gap-2.5 mb-6">
          {[
            { label: 'Correct', value: result.score, color: 'text-emerald-400', icon: '✅' },
            { label: 'Wrong', value: result.total - result.score, color: 'text-red-400', icon: '❌' },
            { label: 'Time', value: formatTime(result.timeTaken), color: 'text-teal-400', icon: '⏱️' },
            { label: 'Date', value: new Date(result.date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' }), color: 'text-amber-400', icon: '📅' },
          ].map((stat, i) => (
            <div key={i} className="glass-card rounded-2xl p-3 text-center">
              <div className="text-lg mb-0.5">{stat.icon}</div>
              <div className={`text-lg font-black ${stat.color}`}>{stat.value}</div>
              <div className="text-[9px] text-gray-600 font-bold uppercase tracking-wider">{stat.label}</div>
            </div>
          ))}
        </div>

        <div className="glass-card rounded-3xl p-5 mb-5">
          <h3 className="font-black text-sm mb-4 flex items-center gap-2">
            <div className="w-7 h-7 bg-teal-500/20 rounded-lg flex items-center justify-center text-sm">📊</div>
            Module Performance
          </h3>
          <div className="space-y-3">
            {Object.entries(result.moduleScores).filter(([, s]) => s.total > 0).map(([module, scores]) => {
              const pct = Math.round((scores.correct / scores.total) * 100);
              const info = getModuleInfo(module);
              return (
                <div key={module} className="flex items-center gap-3">
                  <span className="text-lg w-7 text-center">{info.icon}</span>
                  <div className="flex-1">
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-[11px] font-semibold">{info.name}</span>
                      <span className={`text-[11px] font-black ${pct >= 80 ? 'text-emerald-400' : pct >= 60 ? 'text-amber-400' : 'text-red-400'}`}>
                        {scores.correct}/{scores.total} ({pct}%)
                      </span>
                    </div>
                    <div className="h-2 bg-white/5 rounded-full overflow-hidden">
                      <div className={`h-full rounded-full transition-all duration-1000 ${pct >= 80 ? 'bg-gradient-to-r from-emerald-500 to-green-400' : pct >= 60 ? 'bg-gradient-to-r from-amber-500 to-yellow-400' : 'bg-gradient-to-r from-red-500 to-pink-400'}`}
                        style={{ width: `${pct}%` }}></div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-5">
          {weakAreas.length > 0 && (
            <div className="glass-card rounded-2xl p-4 border-red-500/10">
              <h4 className="font-black text-xs text-red-400 mb-2 flex items-center gap-1.5">📉 Weak Areas</h4>
              <div className="space-y-1.5">{weakAreas.map(m => {
                const info = getModuleInfo(m);
                return (
                  <div key={m} className="flex items-center gap-2 text-xs text-red-300/80 bg-red-500/5 rounded-xl px-3 py-2 border border-red-500/10">
                    <span>{info.icon}</span><span>{info.name}</span>
                  </div>
                );
              })}</div>
            </div>
          )}
          {strongAreas.length > 0 && (
            <div className="glass-card rounded-2xl p-4 border-emerald-500/10">
              <h4 className="font-black text-xs text-emerald-400 mb-2 flex items-center gap-1.5">📈 Strong Areas</h4>
              <div className="space-y-1.5">{strongAreas.map(m => {
                const info = getModuleInfo(m);
                return (
                  <div key={m} className="flex items-center gap-2 text-xs text-emerald-300/80 bg-emerald-500/5 rounded-xl px-3 py-2 border border-emerald-500/10">
                    <span>{info.icon}</span><span>{info.name}</span>
                  </div>
                );
              })}</div>
            </div>
          )}
        </div>

        <div className="glass-card rounded-3xl p-5 mb-5">
          <h3 className="font-black text-sm mb-3 flex items-center gap-2">
            <div className="w-7 h-7 bg-amber-500/20 rounded-lg flex items-center justify-center text-sm">🏅</div>
            Badges Earned
          </h3>
          <div className="flex flex-wrap gap-2">
            {result.percentage >= 90 && (
              <div className="bg-gradient-to-r from-yellow-500/15 to-amber-500/15 border border-yellow-500/25 rounded-2xl px-4 py-2.5 flex items-center gap-2 animate-bounce-in">
                <span className="text-xl">🏆</span><span className="text-[11px] font-black text-yellow-300">Gold EMT</span>
              </div>
            )}
            {result.percentage >= 75 && (
              <div className="bg-gradient-to-r from-teal-500/15 to-cyan-500/15 border border-teal-500/25 rounded-2xl px-4 py-2.5 flex items-center gap-2 animate-bounce-in" style={{ animationDelay: '0.1s' }}>
                <span className="text-xl">🥈</span><span className="text-[11px] font-black text-teal-300">Competent</span>
              </div>
            )}
            {result.percentage === 100 && (
              <div className="bg-gradient-to-r from-emerald-500/15 to-green-500/15 border border-emerald-500/25 rounded-2xl px-4 py-2.5 flex items-center gap-2 animate-bounce-in" style={{ animationDelay: '0.2s' }}>
                <span className="text-xl">💎</span><span className="text-[11px] font-black text-emerald-300">Perfect</span>
              </div>
            )}
            {result.timeTaken < 600 && result.percentage >= 70 && (
              <div className="bg-gradient-to-r from-cyan-500/15 to-teal-500/15 border border-cyan-500/25 rounded-2xl px-4 py-2.5 flex items-center gap-2 animate-bounce-in" style={{ animationDelay: '0.15s' }}>
                <span className="text-xl">⚡</span><span className="text-[11px] font-black text-cyan-300">Speed Star</span>
              </div>
            )}
            {weakAreas.length === 0 && result.percentage >= 70 && (
              <div className="bg-gradient-to-r from-green-500/15 to-emerald-500/15 border border-green-500/25 rounded-2xl px-4 py-2.5 flex items-center gap-2 animate-bounce-in" style={{ animationDelay: '0.2s' }}>
                <span className="text-xl">🎯</span><span className="text-[11px] font-black text-green-300">Well Rounded</span>
              </div>
            )}
            {result.percentage < 60 && (
              <div className="bg-gradient-to-r from-orange-500/15 to-amber-500/15 border border-orange-500/25 rounded-2xl px-4 py-2.5 flex items-center gap-2">
                <span className="text-xl">📚</span><span className="text-[11px] font-black text-orange-300">Keep Learning</span>
              </div>
            )}
          </div>
        </div>

        <div className="glass-card rounded-3xl overflow-hidden mb-5">
          <button onClick={() => setShowDetails(!showDetails)} className="w-full flex items-center justify-between p-5 hover:bg-white/[0.02] transition-colors">
            <h3 className="font-black text-sm flex items-center gap-2">
              <div className="w-7 h-7 bg-teal-500/20 rounded-lg flex items-center justify-center text-sm">📝</div>
              Answer Review
            </h3>
            <span className={`text-gray-500 text-xs transition-transform ${showDetails ? 'rotate-180' : ''}`}>▼</span>
          </button>
          {showDetails && (
            <div className="border-t border-white/5 p-4 space-y-3 max-h-[500px] overflow-y-auto">
              {result.answers.map((answer, idx) => {
                const question = allQuestions.find(q => q.id === answer.questionId);
                if (!question) return null;
                return (
                  <div key={idx} className={`p-4 rounded-2xl border ${answer.isCorrect ? 'bg-emerald-500/5 border-emerald-500/15' : 'bg-red-500/5 border-red-500/15'}`}>
                    <div className="flex items-start gap-2.5">
                      <div className={`w-7 h-7 rounded-lg flex items-center justify-center shrink-0 text-xs font-black ${answer.isCorrect ? 'bg-emerald-500/20 text-emerald-400' : 'bg-red-500/20 text-red-400'}`}>
                        {answer.isCorrect ? '✓' : '✗'}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-xs font-semibold mb-2 leading-relaxed">
                          <span className="text-gray-600 font-mono mr-1.5">Q{idx + 1}.</span>
                          {question.question}
                        </p>
                        {!answer.isCorrect && (
                          <div className="space-y-1 text-[11px] mb-2">
                            {answer.selected >= 0 && <p className="text-red-400/80">✗ Your answer: {question.options[answer.selected]}</p>}
                            <p className="text-emerald-400/80">✓ Correct: {question.options[answer.correct]}</p>
                          </div>
                        )}
                        <p className="text-[11px] text-gray-500 italic leading-relaxed">💡 {question.explanation}</p>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        <div className="grid grid-cols-2 gap-3 mb-3">
          <button onClick={onRetest} className="bg-gradient-to-r from-teal-600 to-emerald-500 hover:from-teal-500 hover:to-emerald-400 rounded-2xl py-4 font-black text-sm flex items-center justify-center gap-2 transition-all active:scale-[0.98] shadow-lg shadow-teal-600/15">
            🔄 Retest
          </button>
          <button onClick={downloadCertificate} className={`rounded-2xl py-4 font-black text-sm flex items-center justify-center gap-2 transition-all active:scale-[0.98] ${
            result.percentage >= 70 ? 'bg-gradient-to-r from-emerald-600 to-green-500 hover:from-emerald-500 hover:to-green-400 shadow-lg shadow-emerald-600/15' : 'bg-white/5 text-gray-600 cursor-not-allowed'
          }`}>
            📄 Certificate
          </button>
        </div>
        <button onClick={onHome} className="w-full glass hover:bg-white/10 rounded-2xl py-3.5 font-bold text-sm flex items-center justify-center gap-2 transition-all active:scale-[0.98]">
          🏠 Home
        </button>
      </div>
    </div>
  );
};

export default ResultScreen;
